"""
Reusable batch data collection + technical scoring script for signal-trader.

Usage:
  1. Set SIGNAL_CODES and SIGNAL_CONF at the top for today's run
  2. Run: python3 collect-batch-researcher-data.py
  3. Gets stock_snapshot, daily_basic_range (20d), moneyflow_summary for all codes
  4. Outputs technical scores and ranking

Handles:
  - Rate limiting (0.3s between calls)
  - MCP response structure differences (stock_snapshot has data.stock/data.quote, not items[])
  - daily_basic_range items are in reverse chronological order (items[0]=latest)
  - None/0 values in numeric fields
  - 300663.SZ 科蓝软件 style crash anomalies (pct < -15%)

See signal-trader SKILL.md for scoring methodology.
"""

import subprocess, json, time

# === CONFIGURE THESE FOR TODAY ===
TRADE_DATE = "2026-05-06"
MF_START_DATE = "2026-04-22"  # 10 trading days before TRADE_DATE
DB_START_DATE = "2026-04-10"  # 20 trading days before TRADE_DATE
MIN_CONFIDENCE = 0.62

# Signal codes + confidence from prediction_results
# (generated by get_prediction_results(query_type="by_trade_date", trade_date=TRADE_DATE))
SIGNAL_CODES = []
SIGNAL_CONF = {}

# === END CONFIG ===

def tushare_call(name, args):
    params = json.dumps({"jsonrpc":"2.0","id":1,"method":"tools/call","params":{"name":name,"arguments":args}})
    cmd = f"""curl -s -X POST http://172.24.144.1:8001/mcp \
      -H 'Content-Type: application/json' -d '{params}'"""
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=15)
    rpc = json.loads(r.stdout)
    return json.loads(rpc["result"]["content"][0]["text"])


def fetch_signals():
    """Fetch signals from get_prediction_results when SIGNAL_CODES is empty."""
    if SIGNAL_CODES:
        return
    
    print(f"Fetching signals for trade_date={TRADE_DATE}...")
    r = tushare_call("get_prediction_results", {
        "query_type": "by_trade_date",
        "trade_date": TRADE_DATE,
        "limit": 500
    })
    items = r.get("data", {}).get("items", [])
    
    for s in items:
        if s["prediction"] == 1 and s.get("probability_up", 0) > MIN_CONFIDENCE:
            SIGNAL_CODES.append(s["ts_code"])
            SIGNAL_CONF[s["ts_code"]] = s["probability_up"]
    
    SIGNAL_CODES.sort(key=lambda c: -SIGNAL_CONF[c])
    print(f"Found {len(SIGNAL_CODES)} signals with probability_up > {MIN_CONFIDENCE}\n")


def collect_snapshots():
    """Get stock snapshot for each signal code."""
    print(f"\n=== STOCK SNAPSHOTS ({len(SIGNAL_CODES)} stocks) ===")
    snapshots = {}
    for code in SIGNAL_CODES:
        r = tushare_call("get_stock_snapshot", {"ts_code": code, "trade_date": TRADE_DATE})
        snapshots[code] = r
        stock = r.get("data", {}).get("stock", {})
        quote = r.get("data", {}).get("quote", {})
        name = stock.get("name", "?")
        close = quote.get("close", "?")
        pct = quote.get("pct_chg", "?")
        vol = quote.get("vol_hand", "?")
        print(f"{code:12s} {name:10s} close={close:>8} pct={pct:>8} vol={vol:>8}")
        time.sleep(0.3)
    return snapshots


def collect_daily_basic():
    """Get 20-day daily_basic for position analysis."""
    print(f"\n=== DAILY BASIC (20d) ===")
    dailies = {}
    for code in SIGNAL_CODES:
        r = tushare_call("get_daily_basic_range", {
            "ts_code": code,
            "start_date": DB_START_DATE,
            "end_date": TRADE_DATE
        })
        dailies[code] = r
        items = r.get("data", {}).get("items", [])
        if items and len(items) >= 5:
            closes = [i["close"] for i in items[:20]]
            latest = items[0]
            high = max(closes)
            low = min(closes)
            pos = (closes[0] - low) / (high - low) * 100 if high > low else 50
            ma5 = sum(closes[:5]) / min(5, len(closes))
            ma20 = sum(closes[:min(20, len(closes))]) / min(20, len(closes))
            vol_r = latest.get("volume_ratio", 0) or 0
            print(f"{code:12s} close={latest['close']:>8.2f} pos={pos:5.1f}% ma5={ma5:>8.2f} ma20={ma20:>8.2f} vol_r={vol_r:>5.2f}")
        else:
            print(f"{code:12s} ⚠️ insufficient data ({len(items) if items else 0} items)")
        time.sleep(0.3)
    return dailies


def collect_moneyflow():
    """Get 10-day moneyflow summary."""
    print(f"\n=== MONEYFLOW SUMMARY (10d) ===")
    moneyflows = {}
    for code in SIGNAL_CODES:
        r = tushare_call("get_moneyflow_summary", {
            "ts_code": code,
            "start_date": MF_START_DATE,
            "end_date": TRADE_DATE
        })
        moneyflows[code] = r
        d = r.get("data", {})
        summary = d.get("summary", {})
        latest = d.get("latest_day", {})
        if summary:
            net_main = summary.get("main_net_amount_total_wan", 0) or 0
            latest_net = latest.get("net_mf_amount_wan", 0) or 0
            latest_elg = (latest.get("buy_elg_amount_wan", 0) or 0) - (latest.get("sell_elg_amount_wan", 0) or 0)
            print(f"{code:12s} 5d_net={net_main:>+8.0f} last_net={latest_net:>+8.0f} last_elg={latest_elg:>+8.0f}")
        else:
            print(f"{code:12s} ⚠️ no data")
        time.sleep(0.3)
    return moneyflows


def compute_technical_score(code, snapshot, daily, moneyflow, conf):
    """Compute technical score (0-10) for 3-day holding."""
    s = snapshot.get("data", {}).get("quote", {})
    d_items = daily.get("data", {}).get("items", [])
    mf_data = moneyflow.get("data", {})
    
    close = s.get("close", 0) or 0
    pct = s.get("pct_chg", 0) or 0
    
    # Direction (0-4)
    if pct < -15:
        dir_score = 0
    elif pct < -5:
        dir_score = 3  # oversold
    elif pct < -2:
        dir_score = 2
    elif pct < 0:
        dir_score = 1
    elif pct < 0.5:
        dir_score = 2
    elif pct < 2:
        dir_score = 3
    else:
        dir_score = 2  # chase risk
    
    # Moneyflow (0-3)
    last_net = (mf_data.get("latest_day", {}) or {}).get("net_mf_amount_wan", 0) or 0
    elg = ((mf_data.get("latest_day", {}) or {}).get("buy_elg_amount_wan", 0) or 0) - \
          ((mf_data.get("latest_day", {}) or {}).get("sell_elg_amount_wan", 0) or 0)
    
    if last_net > 500 and elg > 0:
        mf_score = 3
    elif last_net > 200:
        mf_score = 2
    elif last_net > -200:
        mf_score = 1
    else:
        mf_score = -1 if (mf_data.get("summary", {}) or {}).get("main_net_amount_total_wan", 0) or 0 < -2000 else 0
    
    # Position (0-3)
    closes = [i["close"] for i in d_items[:20]] if d_items else [close]
    high = max(closes) if closes else close
    low = min(closes) if closes else close
    pos = (close - low) / (high - low) * 100 if high > low else 50
    
    if pos < 30:
        pos_score = 3
    elif pos < 60:
        pos_score = 2
    elif pos < 80:
        pos_score = 1
    else:
        pos_score = 0
    
    # Below MA20 bonus
    ma20 = sum(closes[:min(20, len(closes))]) / min(20, len(closes)) if closes else close
    if close < ma20:
        pos_score = min(3, pos_score + 1)
    
    total = max(0, min(10, dir_score + mf_score + pos_score))
    if pct < -15:
        total = 0
    
    return total, dir_score, mf_score, pos_score, pos


def collect_risk_digest(top_codes):
    """Get risk assessment for top candidates (uses get_risk_digest which doesn't need API key)."""
    print(f"\n=== RISK DIGEST ===")
    risks = {}
    for code in top_codes:
        r = tushare_call("get_risk_digest", {"ts_code": code})
        d = r.get("data", {})
        items = d.get("items", [])
        if items:
            item = items[0]
            level = item.get("risk_level_cn", "?")
            summary = item.get("risk_summary", "")[:60]
            print(f"{code:12s} risk={level} | {summary}")
            risks[code] = item
        else:
            print(f"{code:12s} no risk data")
            risks[code] = None
        time.sleep(0.5)
    return risks


if __name__ == "__main__":
    fetch_signals()
    if not SIGNAL_CODES:
        print("No signals found! Exiting.")
        exit(1)
    
    snapshots = collect_snapshots()
    dailies = collect_daily_basic()
    moneyflows = collect_moneyflow()
    
    # Score and rank
    results = []
    for code in SIGNAL_CODES:
        total, di, mfi, pi, pos = compute_technical_score(
            code, snapshots.get(code, {}), dailies.get(code, {}),
            moneyflows.get(code, {}), SIGNAL_CONF.get(code, 0)
        )
        name = snapshots.get(code, {}).get("data", {}).get("stock", {}).get("name", "?")
        results.append((code, name, SIGNAL_CONF.get(code, 0), total, di, mfi, pi, snapshots.get(code, {}).get("data", {}).get("quote", {}).get("close", 0), pos))
    
    results.sort(key=lambda x: -x[3])
    
    print(f"\n{'='*75}")
    print(f"{'排名':>3} {'代码':12s} {'名称':10s} {'总分':>4} {'方向':>3} {'资金':>3} {'位置':>3} {'ModelB':>6} {'价位':>7} {'位置%':>5}")
    print(f"{'-'*75}")
    for i, (code, name, c, total, di, mfi, pi, price, pos) in enumerate(results[:30]):
        print(f"{i+1:3d}. {code:12s} {name:10s} {total:4d} {di:3d} {mfi:3d} {pi:3d} {c:6.4f} {price:>7.2f} {pos:>5.1f}%")
    
    # Top 8 candidates for deeper analysis
    top8 = [r[0] for r in results[:8] if r[3] >= 5]
    if top8:
        collect_risk_digest(top8)
